package com.innowave.mahaulb.repository.inventory.dao.trans;
// Generated Jan 31, 2018 2:32:46 PM  

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.innowave.mahaulb.common.dao.TmUlb;
import com.innowave.mahaulb.repository.inventory.dao.master.TmInvStore;

/**
 * TtInvScrap generated by hbm2java
 */
@Entity
@Table(name = "tt_inv_scrap", schema = "inventory")
public class TtInvScrap implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5972594969363951296L;
	private long scrapId;
	private TmUlb tmUlb;
	private TmInvStore tmInvStore;
	private String scrapNo;
	private Date scrapDate;
	private String scrapRemarks;
	private int scrapCreatedBy;
	private Integer designationId;
	private Character scrapStatus;
	private Integer approvedBy;
	private Date approvedDate;
	private String approvalRemarks;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;
	private String macId;
	private String ipAddress;
	private String deviceFrom;
	private Set<TtInvScrapDet> ttInvScrapDets = new HashSet<TtInvScrapDet>(0);
	private Set<TtInvDisposal> ttInvDisposals = new HashSet<TtInvDisposal>(0);

	public TtInvScrap() {
	}

	public TtInvScrap(long scrapId, TmUlb tmUlb, TmInvStore tmInvStore, String scrapNo, Date scrapDate,
			String scrapRemarks, int scrapCreatedBy, Date createdDate) {
		this.scrapId = scrapId;
		this.tmUlb = tmUlb;
		this.tmInvStore = tmInvStore;
		this.scrapNo = scrapNo;
		this.scrapDate = scrapDate;
		this.scrapRemarks = scrapRemarks;
		this.scrapCreatedBy = scrapCreatedBy;
		this.createdDate = createdDate;
	}

	public TtInvScrap(long scrapId, TmUlb tmUlb, TmInvStore tmInvStore, String scrapNo, Date scrapDate,
			String scrapRemarks, int scrapCreatedBy, Integer designationId, Character scrapStatus, Integer approvedBy,
			Date approvedDate, String approvalRemarks, Integer createdBy, Date createdDate, Integer updatedBy,
			Date updatedDate, String macId, String ipAddress, String deviceFrom, Set<TtInvScrapDet> ttInvScrapDets,
			Set<TtInvDisposal> ttInvDisposals) {
		this.scrapId = scrapId;
		this.tmUlb = tmUlb;
		this.tmInvStore = tmInvStore;
		this.scrapNo = scrapNo;
		this.scrapDate = scrapDate;
		this.scrapRemarks = scrapRemarks;
		this.scrapCreatedBy = scrapCreatedBy;
		this.designationId = designationId;
		this.scrapStatus = scrapStatus;
		this.approvedBy = approvedBy;
		this.approvedDate = approvedDate;
		this.approvalRemarks = approvalRemarks;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.macId = macId;
		this.ipAddress = ipAddress;
		this.deviceFrom = deviceFrom;
		this.ttInvScrapDets = ttInvScrapDets;
		this.ttInvDisposals = ttInvDisposals;
	}

	@Id

	@Column(name = "scrap_id", unique = true, nullable = false)
	public long getScrapId() {
		return this.scrapId;
	}

	public void setScrapId(long scrapId) {
		this.scrapId = scrapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ulb_id", nullable = false)
	public TmUlb getTmUlb() {
		return this.tmUlb;
	}

	public void setTmUlb(TmUlb tmUlb) {
		this.tmUlb = tmUlb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id", nullable = false)
	public TmInvStore getTmInvStore() {
		return this.tmInvStore;
	}

	public void setTmInvStore(TmInvStore tmInvStore) {
		this.tmInvStore = tmInvStore;
	}

	@Column(name = "scrap_no", nullable = false, length = 50)
	public String getScrapNo() {
		return this.scrapNo;
	}

	public void setScrapNo(String scrapNo) {
		this.scrapNo = scrapNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "scrap_date", nullable = false, length = 13)
	public Date getScrapDate() {
		return this.scrapDate;
	}

	public void setScrapDate(Date scrapDate) {
		this.scrapDate = scrapDate;
	}

	@Column(name = "scrap_remarks", nullable = false, length = 2000)
	public String getScrapRemarks() {
		return this.scrapRemarks;
	}

	public void setScrapRemarks(String scrapRemarks) {
		this.scrapRemarks = scrapRemarks;
	}

	@Column(name = "scrap_created_by", nullable = false)
	public int getScrapCreatedBy() {
		return this.scrapCreatedBy;
	}

	public void setScrapCreatedBy(int scrapCreatedBy) {
		this.scrapCreatedBy = scrapCreatedBy;
	}

	@Column(name = "designation_id")
	public Integer getDesignationId() {
		return this.designationId;
	}

	public void setDesignationId(Integer designationId) {
		this.designationId = designationId;
	}

	@Column(name = "scrap_status", length = 1)
	public Character getScrapStatus() {
		return this.scrapStatus;
	}

	public void setScrapStatus(Character scrapStatus) {
		this.scrapStatus = scrapStatus;
	}

	@Column(name = "approved_by")
	public Integer getApprovedBy() {
		return this.approvedBy;
	}

	public void setApprovedBy(Integer approvedBy) {
		this.approvedBy = approvedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "approved_date", length = 13)
	public Date getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	@Column(name = "approval_remarks", length = 2000)
	public String getApprovalRemarks() {
		return this.approvalRemarks;
	}

	public void setApprovalRemarks(String approvalRemarks) {
		this.approvalRemarks = approvalRemarks;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "mac_id", length = 50)
	public String getMacId() {
		return this.macId;
	}

	public void setMacId(String macId) {
		this.macId = macId;
	}

	@Column(name = "ip_address", length = 50)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "device_from", length = 1)
	public String getDeviceFrom() {
		return this.deviceFrom;
	}

	public void setDeviceFrom(String deviceFrom) {
		this.deviceFrom = deviceFrom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ttInvScrap")
	public Set<TtInvScrapDet> getTtInvScrapDets() {
		return this.ttInvScrapDets;
	}

	public void setTtInvScrapDets(Set<TtInvScrapDet> ttInvScrapDets) {
		this.ttInvScrapDets = ttInvScrapDets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ttInvScrap")
	public Set<TtInvDisposal> getTtInvDisposals() {
		return this.ttInvDisposals;
	}

	public void setTtInvDisposals(Set<TtInvDisposal> ttInvDisposals) {
		this.ttInvDisposals = ttInvDisposals;
	}

}
